version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/app
    links:
     - db
    environment:
     - DATABASE_HOST=db
     - DATABASE_PORT=5432
     - DATABASE_USER=nodal
     - DATABASE_PASSWORD=nodal
     - DATABASE_DB=nodal_development
  db:
    image: postgres
    environment:
     - POSTGRES_USER=nodal
     - POSTGRES_PASSWORD=nodal
     - POSTGRES_DB=nodal_development
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    links:
      - web
